name: build

on:
  pull_request:
  push:
    branches: [main]
  merge_group:

jobs:
  build-image:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: install nix
        uses: cachix/install-nix-action@v20
        with:
          nix_path: nixpkgs=channel:nixos-unstable
          extra_nix_config: |
            extra-platforms = aarch64-linux arm-linux

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: build image
        run: ./build-image.cross.sh
